#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
LOCAL_DIR="${ROOT_DIR}/.local"
SDK_DIR="${OHOS_SDK_DIR:-${LOCAL_DIR}/ohos-sdk}"
SDK_VERSION="${OHOS_SDK_VERSION:-5.0.0-Release}"
SDK_URL="https://mirrors.huaweicloud.com/openharmony/os/${SDK_VERSION}/ohos-sdk-windows_linux-public.tar.gz"
SDK_FILE="${LOCAL_DIR}/ohos-sdk.tar.gz"
ENV_FILE="${LOCAL_DIR}/ohos-env.sh"

INSTALL_DEPS=0
if [[ "${1:-}" == "--install-deps" ]]; then
  INSTALL_DEPS=1
fi

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || return 1
}

check_deps() {
  local missing=()
  for cmd in cmake ninja git wget curl unzip python3 nasm yasm autoconf automake libtool patchelf tar; do
    if ! need_cmd "$cmd"; then
      missing+=("$cmd")
    fi
  done
  if ((${#missing[@]} > 0)); then
    echo "Missing tools: ${missing[*]}"
    if ((INSTALL_DEPS == 1)); then
      echo "Installing build dependencies via apt-get..."
      sudo apt-get update
      sudo apt-get install -y \
        build-essential cmake ninja-build pkg-config git wget curl unzip \
        python3 nasm yasm autoconf automake libtool patchelf
    else
      echo "Run with --install-deps to install via apt-get, or install them manually."
      return 1
    fi
  fi
}

mkdir -p "${LOCAL_DIR}"

check_deps

if [[ -d "${SDK_DIR}" ]]; then
  echo "SDK dir already exists: ${SDK_DIR}"
else
  mkdir -p "${SDK_DIR}"
fi

if [[ ! -f "${SDK_FILE}" ]]; then
  echo "Downloading OpenHarmony SDK: ${SDK_URL}"
  for i in 1 2 3; do
    echo "Download attempt ${i}..."
    if curl -L --retry 3 --retry-delay 5 -o "${SDK_FILE}" "${SDK_URL}"; then
      if tar -tzf "${SDK_FILE}" >/dev/null 2>&1; then
        echo "Archive is valid"
        break
      fi
    fi
    rm -f "${SDK_FILE}"
    sleep 10
    if [[ $i -eq 3 ]]; then
      echo "ERROR: Failed to download SDK"
      exit 1
    fi
  done
fi

echo "Extracting SDK..."
mkdir -p "${SDK_DIR}"
if [[ ! -d "${SDK_DIR}/linux" ]]; then
  tar xzf "${SDK_FILE}" -C "${SDK_DIR}"
fi

if [[ -d "${SDK_DIR}/linux" ]]; then
  echo "Unzipping linux SDK packages..."
  (cd "${SDK_DIR}/linux" && for f in *.zip; do unzip -q "$f" -d "${SDK_DIR}"; done)
fi

NATIVE_DIR=$(find "${SDK_DIR}" -maxdepth 1 -type d -name "native*" | head -1 || true)
if [[ -z "${NATIVE_DIR}" ]]; then
  echo "ERROR: Native SDK not found in ${SDK_DIR}"
  ls -la "${SDK_DIR}"
  exit 1
fi

echo "Native SDK: ${NATIVE_DIR}"
cat > "${ENV_FILE}" <<EOF2
# Auto-generated by scripts/linux-setup.sh
export OHOS_NDK_HOME="${NATIVE_DIR}"
EOF2

echo "Wrote environment file: ${ENV_FILE}"

echo "Setup complete. Next: run scripts/linux-build.sh"
